"""changed project model

Revision ID: 0629ef576bff
Revises: 5966eaef936d
Create Date: 2023-04-26 08:44:15.278695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0629ef576bff'
down_revision = '5966eaef936d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
