"""added clients_id null to task

Revision ID: 1cf1a541946d
Revises: d5cfd872281b
Create Date: 2023-05-16 14:56:44.059055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf1a541946d'
down_revision = 'd5cfd872281b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
