"""added booleans

Revision ID: 4b37cb17ae39
Revises: 78bc788f4fcd
Create Date: 2023-04-25 06:31:07.396035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b37cb17ae39'
down_revision = '78bc788f4fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('complete')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
