"""Task update

Revision ID: 724df7258654
Revises: e008cde455b6
Create Date: 2023-07-03 13:32:03.005746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724df7258654'
down_revision = 'e008cde455b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_unique_constraint('tasks_description_key', ['description'])

    # ### end Alembic commands ###
