"""added clients

Revision ID: d5cfd872281b
Revises: 0629ef576bff
Create Date: 2023-05-16 14:30:16.258947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cfd872281b'
down_revision = '0629ef576bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tasks')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_client_id_clients'), 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_client_id_clients'), type_='foreignkey')
        batch_op.drop_column('client_id')

    op.create_table('_alembic_tmp_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('due_date', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_tasks_client_id_clients'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_tasks_project_id_projects'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_tasks_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
